FROM python:3.9
WORKDIR /opt/workdir

COPY backend/requirements.txt backend/backend.py backend/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "backend:app"]
